# This is a basic workflow to help you get started with Actions
name: CI/CD Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  backend:
    name: Backend CI/CD
    runs-on: Linux
    environment: JUNGLE_SECRET
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Set up node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "20.x"

      - name: Create .env file
        run: |
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env 
          echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env 
          echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" >> .env 
          echo "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> .env
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env 
          echo "AWS_BUCKET=${{ secrets.AWS_BUCKET }}" >> .env 
          cat .env

      - name: docker Down
        run: docker compose down

      - name: docker remove image
        run: docker rmi nmm_backend
        continue-on-error: true

      - name: docker up
        run: docker compose up -d --build
